import Head from 'next/head';
import {signIn,signOut,useSession} from 'next-auth/client';
import styles from '../styles/Home.module.css';
import { Image } from 'next/image';

export default function Home(){
  const [session,loadingSession] = useSession();
  if(loadingSession){
    return <p>Loading...</p>
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by created next app"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!session && (
        <>
        <button onClick={()=> signIn()}>SignIn</button>
        </>
      )}

      {session && (
        <>
        <h4>You are Logged as: {session.user.name}</h4>
        <div className={styles.boxCenter}>
          <h4>Email:{session.user.email}</h4>
          <br/>
          {session.user.image && (
            <span>
              <img src={session.user.image} alt={session.user.name}/>
            </span>
          )}
        </div>
        <br/>
        <br/>
        <button className={styles.primarybutton} onClick={()=>signOut()}>
          Sign Out
        </button>
        </>
      )}
    </div>
  )
}